/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndh_ngplayer_NativeCall */

#ifndef _Included_com_ndh_ngplayer_NativeCall
#define _Included_com_ndh_ngplayer_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndh_ngplayer_NativeCall
 * Method:    sprintf
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndh_ngplayer_NativeCall_sprintf(JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
